#!/usr/bin/env python3
"""Generate a C header embedding a PEM trust bundle."""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-pem", required=True, help="Path to the source PEM bundle")
    parser.add_argument("--output-header", required=True, help="Path to the generated C header")
    parser.add_argument("--profile-name", required=True, help="Human-readable TLS profile name")
    return parser.parse_args()


def render_c_string(text: str) -> str:
    lines = text.splitlines()
    rendered: list[str] = []
    for line in lines:
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        rendered.append(f'    "{escaped}\\n"')
    if not rendered:
        rendered.append('    ""')
    return "\n".join(rendered)


def main() -> int:
    args = parse_args()
    input_path = Path(args.input_pem)
    output_path = Path(args.output_header)
    pem_text = input_path.read_text(encoding="utf-8")
    if "-----BEGIN CERTIFICATE-----" not in pem_text:
        raise SystemExit(f"no certificate blocks found in {input_path}")

    rendered_bundle = render_c_string(pem_text)
    content = f"""// Generated by scripts/logger_tls_codegen.py.
// Source PEM bundle: {input_path}
// TLS profile: {args.profile_name}

#ifndef LOGGER_FIRMWARE_UPLOAD_TLS_ROOTS_H
#define LOGGER_FIRMWARE_UPLOAD_TLS_ROOTS_H

static const char logger_upload_tls_ca_bundle_pem[] =
{rendered_bundle};

#endif
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
